Feature/place cud
wecode-bootcamp-korea/14-1st-OurPlays-backend pull request #5
Opened 2020-11-19 07:09 UTC by jinybear

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- settings.py의 Database, SECRET_KEY 설정시 my_settings.py 참조하도록 수정
- place 에 대한 추가/수정/삭제 요청에 대해 urls, views 측 구현
- models의 일부 오타 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 예외처리로 인해 exception 메시지를 못보는 상황이 발생하고 있습니다. django 에서 logging 사용법을 찾고 있는데 알려주시면 감사하겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-20 07:51 UTC, ulfrid requested changes
수정부탁드립니다.

2020-11-20 07:51 UTC, devops-andrew commented on place/models.py
> +    price_per_hour              = models.IntegerField(default=10000)
```suggestion
    price_per_hour              = models.DecimalField(default=10000 ,max_digits=7, decimal_places=2)
```
비용은 실수 처리해주세요. 소수점 두자리까지 주세요.

2020-11-20 07:51 UTC, devops-andrew commented on place/urls.py
> +
잘하셨습니다 👍🏻

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +    #@checkAuthDecorator
아래에 보면 데코레이터가 있는데 반영이 안된건가요? 데코레이터 코드는 본인의 작성 영역이 아닌가요?

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +                        ).save()
bulk_create를 해보세요 
https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-create

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +                    ).save()
마찬가지 입니다.

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +        except Exception as ex:
이런 익셉션은 도움되지 않습니다. 
필요한 익셉션만 걸어주세요.

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status = 201)
코드 흐름상 익셉션 코드보다 위에 있어야 흐름에 맞습니다.

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +        except Exception as ex:
제거 해주세요~!

2020-11-20 07:51 UTC, ulfrid commented on place/views.py
> +
위의 코드는 뭔가 로직의 동선이 미완성으로 느껴지는데 설명이 필요합니다. 현장 리뷰를 요청드립니다.

2020-11-20 08:24 UTC, jinybear commented on place/urls.py
> +
감사합니다 :)

2020-11-20 08:24 UTC, jinybear commented on place/models.py
> +    price_per_hour              = models.IntegerField(default=10000)
수정하겠습니다

2020-11-20 08:25 UTC, jinybear commented on place/views.py
> +    #@checkAuthDecorator
팀원인 영주님이 Token 관련 작업을 하고 계셔서 merge가 되면 일괄 적용할 예정이었습니다.

2020-11-20 09:25 UTC, jinybear commented on place/views.py
> +                        ).save()
오 이런 성능차이가 있었군요. +o+  말씀 감사합니다.

2020-11-20 12:15 UTC, jinybear commented on place/views.py
> +                    ).save()
넵

2020-11-20 12:16 UTC, jinybear commented on place/views.py
> +        except Exception as ex:
예외 세분화 처리 하겠습니다

2020-11-20 12:16 UTC, jinybear commented on place/views.py
> +
self.model.DoesNotExist 를 Place.DoesNotExist로 수정했습니다

2020-11-20 12:17 UTC, jinybear commented on place/views.py
> +        except Exception as ex:
네

2020-11-21 05:25 UTC, ulfrid requested changes
추가 수정 부탁드립니다.

2020-11-21 05:25 UTC, ulfrid commented on place/views.py
> +            PlaceImage.objects.bulk_create(bulk_list)
위코드는 다시한번 파이써닉하게 변경할 수 있는데요!
list comprehension 을 아시나요?

```
PlaceImage.object.bulk_create(
    [
        PlaceImage(
            url          = image['url'],
            place_id = place.id
        ) for image in data['images']
    ]
) 
```

2020-11-21 05:25 UTC, ulfrid commented on place/views.py
> +            for day in data['invalid_dates']:
클리어 해서 재사용하지 마시고 List Comprehension으로 변경해주세요.

2020-11-21 05:26 UTC, ulfrid commented on place/views.py
> +    #@checkAuthDecorator
넵

2020-11-21 05:26 UTC, ulfrid commented on place/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status = 201)
정상리턴을 exception보다 위로 올려주세요.

2020-11-21 06:16 UTC, jinybear commented on place/views.py
> +            for day in data['invalid_dates']:
넵

2020-11-21 06:21 UTC, jinybear commented on place/views.py
> +            PlaceImage.objects.bulk_create(bulk_list)
네 알고 있습니다. 적용해 보겠습니다

2020-11-23 01:22 UTC, soheon-lee commented on place/models.py
> +    name                        = models.CharField(max_length=50, unique=True)
```suggestion
    name = models.CharField(max_length=50, unique=True)
```
이렇게 띄우시진 않으셔도 됩니다. 코드 간격은 같은 클래스 내부나 같은 함수 내부에서만 지켜주시면 됩니다 👍

2020-11-23 01:22 UTC, soheon-lee commented on place/views.py
> +                                                    )
```suggestion
                        place_id = place.id,
                        day      = datetime.strptime(day['date'], '%Y-%m-%d')
```
인자가 두가지 뿐이라 한 줄로 합치시는게 가독성이 더 높을 것 같습니다.

2020-11-23 01:22 UTC, soheon-lee commented on place/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status = 201)
여기 return도 코드의 흐름상 152번줄정도로 옮겨지면 좋을 것 같습니다. 코드가 자연스레 에러없이 잘 진행되면 바로 success를 만나는 것이 좋고, 그 예외의 상황인 except가 더 아래에 있는 것이 자연스럽습니다 :)

2020-11-23 01:34 UTC, jinybear commented on place/models.py
> +    name                        = models.CharField(max_length=50, unique=True)
넵 반영하겠습니다

2020-11-23 01:35 UTC, jinybear commented on place/views.py
> +                                                    )
넵 반영하겠습니다

2020-11-23 01:36 UTC, jinybear commented on place/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status = 201)
넵. 일괄 반영하겠습니다

2020-11-23 08:31 UTC, soheon-lee commented on place/models.py
> +    place      = models.ForeignKey(Place, on_delet = models.CASCADE, related_name = 'related_rating_place')
```suggestion
    place      = models.ForeignKey(Place, on_delete = models.CASCADE, related_name = 'related_rating_place')
```

2020-11-23 13:14 UTC, jinybear commented on place/models.py
> +    place      = models.ForeignKey(Place, on_delet = models.CASCADE, related_name = 'related_rating_place')
읔... 죄송합니다 이런 실수를;; 바로 수정하겠습니다

2020-11-24 06:32 UTC, soheon-lee commented on place/urls.py
> +        path('/delete_place', DeletePlaceView.as_view()),
REST에 맞는 api 주소로 변경 부탁드립니다 :)

2020-11-24 06:32 UTC, soheon-lee commented on place/views.py
> +            user_id    = token #get_value_from_token(token, 'user_id')
사용하지 않는 주석은 제거해주세요

2020-11-24 06:32 UTC, soheon-lee commented on place/views.py
> +                target_tag.places_tags.add(place)
good! 장고에는 객체를 get 해오거나 없으면 create 해주는 기능을 지원하는 함수가 있습니다 :) 그 함수를 한 번 활용해보세요~

2020-11-24 06:33 UTC, soheon-lee commented on place/views.py
> +                target_tag.places_tags.add(place)
여기도 get 하거나 없으면 create 하는 메소드를 사용하여 한 번에 해결해주세요 :)

2020-11-24 06:59 UTC, jinybear commented on place/views.py
> +                target_tag.places_tags.add(place)
넵 반영하겠습니다

2020-11-24 06:59 UTC, jinybear commented on place/views.py
> +                target_tag.places_tags.add(place)
넵 반영하겠습니다

2020-11-24 07:46 UTC, jinybear commented on place/urls.py
> +        path('/delete_place', DeletePlaceView.as_view()),
예압

2020-11-24 07:46 UTC, jinybear commented on place/views.py
> +            user_id    = token #get_value_from_token(token, 'user_id')
예압

2020-11-24 10:05 UTC, soheon-lee commented on place/views.py
> +            user_id    = token
decorator가 이제 기능할 수 있을 것으로 알고 있습니다. 현재 token을 모든 엔드포인트에서 받아오고 있는 부분을 이제 데코레이터를 통해 동작하게끔 변경해주세요 :)

2020-11-24 10:36 UTC, jinybear commented on place/views.py
> +            user_id    = token
옛썰

2020-11-25 03:42 UTC, soheon-lee commented
LGTM !!! 고생하셨습니다 승진님

2020-11-25 03:42 UTC, merged