[ADD]회원가입 및 로그인
wecode-bootcamp-korea/14-1st-OurPlays-backend pull request #6
Opened 2020-11-19 07:11 UTC by 097kim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-19 11:39 UTC, soheon-lee requested changes

2020-11-19 11:39 UTC, soheon-lee commented on reservation/models.py
> +    place_id               = models.ForeignKey('place.Place', on_delete=models.CASCADE)
`_id` 붙이고 migration 하고나서 테이블 컬럼 확인해보셨나요?? 컬럼 이름이 좀 이상할텐데 한 번 확인 부탁드립니다~

2020-11-19 11:39 UTC, soheon-lee commented on share/decorators.py
> +​
```suggestion
from user.models import (
    User,
)
from my_settings import (
    SECRET,
    ALGORITHM,
)​
```
간격 조정해주시면 더 좋을 것 같아요~

2020-11-19 11:39 UTC, soheon-lee commented on share/decorators.py
> +def checkAuthDecorator(func):
파이썬에서는 함수 이름을 camelCase로 지정하지 않습니다. snake_case로 변경해주세요

2020-11-19 11:39 UTC, soheon-lee commented on user/views.py
> +            if bcrypt.checkpw(data['password'].encode('utf-8'), user_data.values()[0]['password'].encode('utf-8')):
```suggestion
            if bcrypt.checkpw(data['password'].encode('utf-8'), user_data.get().password.encode('utf-8')):
```
쿼리셋에 단 하나의 객체만 존재할 때에는 `get()` 메소드를 활용하시면 `[0]`으로 인덱싱을 하지 않아도 해당 객체를 가져오실 수 있고, 그러면 password라는 속성에 접근할 수 있습니다 :) 객체의 형태로 데이터를 다뤄보는 것을 추천드립니다 :)

2020-11-19 11:39 UTC, soheon-lee commented on user/views.py
> +                signin_token = jwt.encode({'email':user_data.values()[0]['email']}, 'SECRET_KEY', algorithm='HS256')
Token 암호화 알고리즘이 노출되었습니다. 보안에 굉장히 취약해지니 secret_key와 마찬가지로 별도의 모듈로 분리시켜 관리해주세요 :)

2020-11-19 11:39 UTC, soheon-lee commented on user/views.py
> +                signin_token = jwt.encode({'email':user_data.values()[0]['email']}, 'SECRET_KEY', algorithm='HS256')
```suggestion
                signin_token = jwt.encode({'email':user_data.get().email}, 'SECRET_KEY', algorithm='HS256')
```
위 59번 줄의 password와 같은 피드백입니다

2020-11-19 11:39 UTC, soheon-lee commented on user/views.py
> +                signon_token = signin_token.decode('utf-8')
```suggestion
                token = jwt.encode({'email':user_data.values()[0]['email']}, 'SECRET_KEY', algorithm='HS256').decode('utf-8')
```
굳이 두 단계로 분리하지 않고 디코딩까지 한 번에 진행하셔도 좋습니다.

2020-11-24 06:40 UTC, merged

2020-11-24 06:42 UTC, 097kim commented on reservation/models.py
> +    place_id               = models.ForeignKey('place.Place', on_delete=models.CASCADE)
승진님이 수정할 예정입니다!

2020-11-24 06:42 UTC, 097kim commented on share/decorators.py
> +​
승진님이 수정할 예정입니다!

2020-11-24 06:42 UTC, 097kim commented on share/decorators.py
> +def checkAuthDecorator(func):
승진님이 수정할 예정입니다!

2020-11-24 06:42 UTC, 097kim commented on user/views.py
> +                signin_token = jwt.encode({'email':user_data.values()[0]['email']}, 'SECRET_KEY', algorithm='HS256')
넵.. 꽁꽁 숨겨보겠습니다..

2020-11-24 06:42 UTC, 097kim commented on user/views.py
> +            if bcrypt.checkpw(data['password'].encode('utf-8'), user_data.values()[0]['password'].encode('utf-8')):
넵 왜 쓰는지도 모르면서 동기들 어깨에 기대다보니.. 좋아보여서 쓰다보니.. 화근이.. 기초 탄탄 하겠습니다..

2020-11-24 06:42 UTC, 097kim commented on user/views.py
> +                signin_token = jwt.encode({'email':user_data.values()[0]['email']}, 'SECRET_KEY', algorithm='HS256')
메모...

2020-11-24 06:42 UTC, 097kim commented on user/views.py
> +                signon_token = signin_token.decode('utf-8')
넵.. 줄이겠슴다